# Pipeline de build dos códigos

trigger: none

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python-version)'
    addToPath: true
  displayName: 'Versão do Python: $(python-version)'

- task: BatchScript@1
  inputs:
    filename: 'run_files.cmd'
  displayName: 'Gerar Dataset de treinamento'